// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 主文档侧边栏 - 自动生成，包含所有六大分类
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // 自动生成整个 docs 目录的侧边栏
    },
  ],

  // 也可以手动配置侧边栏（如果需要更精细的控制）
  /*
  docsSidebar: [
    {
      type: 'category',
      label: '快速开始',
      link: {
        type: 'generated-index',
        title: '快速开始',
        description: '了解如何快速开始使用我们的产品',
      },
      items: [
        {type: 'autogenerated', dirName: '01-getting-started'},
      ],
    },
    {
      type: 'category',
      label: '用户指南',
      link: {
        type: 'generated-index',
        title: '用户指南',
        description: '详细的功能说明和使用方法',
      },
      items: [
        {type: 'autogenerated', dirName: '02-user-guide'},
      ],
    },
    {
      type: 'category',
      label: 'API 文档',
      link: {
        type: 'generated-index',
        title: 'API 文档',
        description: '完整的 RESTful API 接口文档',
      },
      items: [
        {type: 'autogenerated', dirName: '03-api'},
      ],
    },
    {
      type: 'category',
      label: '部署指南',
      link: {
        type: 'generated-index',
        title: '部署指南',
        description: '了解如何在不同环境中部署应用',
      },
      items: [
        {type: 'autogenerated', dirName: '04-deployment'},
      ],
    },
    {
      type: 'category',
      label: '开发指南',
      link: {
        type: 'generated-index',
        title: '开发指南',
        description: '了解项目架构和如何参与开发',
      },
      items: [
        {type: 'autogenerated', dirName: '05-development'},
      ],
    },
    {
      type: 'category',
      label: '故障排查',
      link: {
        type: 'generated-index',
        title: '故障排查',
        description: '常见问题和解决方案',
      },
      items: [
        {type: 'autogenerated', dirName: '06-troubleshooting'},
      ],
    },
  ],
  */
};

export default sidebars;
